'use client';
import { useEffect,useMemo,useState } from 'react';

type Row={id:string;city:string;district:string;type:string;status:string;price:number;area:number};
type Payload={rows:Row[];stats:{count:number;avgPrice:number;avgPpm:number;cities:string[];districts:string[];types:string[]}};
const money=(n:number)=>`EGP ${Math.round(n).toLocaleString()}`;
export default function Dashboard(){
 const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [ai,setAi]=useState('');const [aiBusy,setAiBusy]=useState(false);
 useEffect(()=>{fetch('/api/properties').then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[]);
 const rows=data?.rows??[];const s=data?.stats;const district=useMemo(()=>Object.entries(rows.reduce<Record<string,number>>((a,r)=>(a[r.district]=(a[r.district]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]).slice(0,6),[rows]);
 async function runAI(){setAiBusy(true);setAi('');try{const r=await fetch('/api/insights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:'Find the most important pricing, demand, anomaly and investment signals. Then give 3 concrete actions for a real-estate decision maker.'})});const j=await r.json();setAi(j.answer||j.insights?.join('\n')||j.error||'No insight returned.')}finally{setAiBusy(false)}}
 return <div className="shell"><header className="top"><div className="brand">Estate<span>IQ</span></div><nav className="nav"><span>Overview</span><span>Analytics</span><span>AI Insights</span></nav><button className="ai" onClick={runAI}>{aiBusy?'Analyzing…':'Run AI analysis'}</button></header><main className="main"><section className="hero"><div><div className="eyebrow">Real-estate intelligence</div><h1>Know what the market<br/>is telling you.</h1><p>One clean workspace for property data, market analytics and autonomous AI insights. Connect Neon when you are ready; demo data keeps the dashboard usable meanwhile.</p></div></section>{loading?<p className="loading">Loading dataset…</p>:<><section className="grid"><div className="card"><div className="label">Properties</div><div className="metric">{s?.count}</div></div><div className="card"><div className="label">Average price</div><div className="metric">{s&&money(s.avgPrice)}</div></div><div className="card"><div className="label">Avg / m²</div><div className="metric">{s&&money(s.avgPpm)}</div></div><div className="card"><div className="label">Districts</div><div className="metric">{s?.districts.length}</div></div></section><section className="content"><div className="card"><div className="label">Listing concentration</div><div className="bars">{district.map(([name,count])=><div className="barwrap" key={name}><div className="bar" style={{height:`${Math.max(10,count/Math.max(...district.map(x=>x[1]))*180)}px`}}/><span>{name}</span></div>)}</div></div><div className="card"><div className="label">AI intelligence</div>{ai?<div className="insight"><span className="tag">QWEN ANALYSIS</span><p style={{whiteSpace:'pre-wrap'}}>{ai}</p></div>:<><div className="insight"><strong>Autonomous analysis</strong><p>Ask the AI to detect pricing opportunities, unusual listings, demand concentration and next actions.</p></div><div className="insight"><strong>Evidence first</strong><p>Insights are generated from the dataset, not generic real-estate advice.</p></div></>}</div></section><div className="card table"><div className="label">Recent properties</div><div className="row head"><span>District</span><span>Type</span><span>Area</span><span>Price</span></div>{rows.slice(0,8).map(r=><div className="row" key={r.id}><span>{r.district}</span><span>{r.type}</span><span>{r.area} m²</span><span>{money(r.price)}</span></div>)}</div></>}</main></div>;
}
