import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes, SVGAttributes, HTMLAttributes } from "react";

export function cn(...classes: Array<string | false | null | undefined>) { return classes.filter(Boolean).join(" "); }
export const paths: Record<string, string> = { home:"M3 10.5L12 3l9 7.5M5.5 9.5V21h13V9.5M9 21v-6h6v6", chart:"M4 19V5M4 19h16M8 16v-4M12 16V8M16 16v-6", spark:"M12 2l1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8L12 2z", building:"M4 21V5h10v16M14 9h6v12M7 8h4M7 12h4M7 16h4M17 13h1M17 17h1", pin:"M12 21s-7-5.5-7-11a7 7 0 1114 0c0 5.5-7 11-7 11zm0-8.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5z", compare:"M7 4v16M7 4l-3 3M7 4l3 3M17 20V4M17 20l-3-3M17 20l3-3", upload:"M12 16V4m0 0L7 9m5-5l5 5M4 14v5h16v-5", layers:"M12 3l8 4-8 4-8-4 8-4zm-8 9l8 4 8-4M4 17l8 4 8-4", doc:"M6 3h8l4 4v14H6V3zm8 0v5h4M9 12h6M9 16h6", bookmark:"M6 4h12v17l-6-3-6 3V4z", user:"M12 12a4 4 0 100-8 4 4 0 000 8zm-7 9a7 7 0 0114 0", logout:"M10 5H5v14h5M14 8l4 4-4 4M18 12H9", x:"M6 6l12 12M18 6L6 18", filter:"M4 5h16M7 12h10M10 19h4", check:"M5 12l4 4L19 6", arrow:"M5 12h14M13 6l6 6-6 6" };
export function Icon({d,size=16,className,strokeWidth=1.7,...props}:{d:string;size?:number;className?:string;strokeWidth?:number}&Omit<SVGAttributes<SVGSVGElement>,"d"|"width"|"height">){return <svg {...props} width={size} height={size} viewBox="0 0 24 24" fill="none" className={className} aria-hidden><path d={d} stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round"/></svg>}
export function Spinner({className,...props}:{className?:string}&HTMLAttributes<HTMLSpanElement>){return <span {...props} className={cn("inline-block h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent",className)} aria-label="Loading"/>}
type ButtonVariant=string;
export function Button({className,size="md",variant="default",...props}:ButtonHTMLAttributes<HTMLButtonElement>&{size?:"sm"|"md"|"lg";variant?:ButtonVariant}){return <button {...props} className={cn("inline-flex items-center justify-center gap-2 rounded-md px-4 font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-50",variant==="default"&&"bg-pine text-cream hover:bg-pine-deep",variant==="gold"&&"bg-gold text-ink hover:bg-gold/90",variant==="ghost"&&"bg-transparent text-ink-2 hover:bg-ink/5",variant==="outline"&&"border border-line bg-transparent text-ink hover:bg-ink/5",variant==="dark"&&"bg-ink text-cream hover:bg-ink/90",size==="sm"&&"h-9 text-[12px]",size==="md"&&"h-10 text-[13px]",size==="lg"&&"h-12 text-[14px]",!(["default","gold","ghost","outline","dark"].includes(variant))&&"bg-pine text-cream hover:bg-pine-deep",className)}/>}
export function Badge({children,className,tone="default"}:{children:ReactNode;className?:string;tone?:string}){return <span className={cn("inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-medium",tone==="default"&&"border border-line bg-card text-ink-2",tone==="outline"&&"border border-line bg-transparent text-ink-2",tone==="gold"&&"border border-gold/30 bg-gold/15 text-ink",tone==="pine"&&"border border-pine/20 bg-pine/10 text-pine",tone==="rust"&&"border border-rust/25 bg-rust-tint text-rust",className)}>{children}</span>}
export function Card({className,...props}:HTMLAttributes<HTMLDivElement>){return <div {...props} className={cn("rounded-lg border border-line bg-card shadow-card",className)}/>}
export function ErrorState({className,message="Something went wrong.",onRetry,retry,...props}:{className?:string;message?:string;onRetry?:()=>void;retry?:()=>void}&HTMLAttributes<HTMLDivElement>){const handleRetry=onRetry ?? retry; return <div {...props} className={cn("rounded-lg border border-line bg-card p-6 text-center",className)}><p className="text-sm text-rust">{message}</p>{handleRetry ? <button onClick={() => { void handleRetry(); }} className="mt-3 text-xs font-medium text-pine underline">Try again</button> : null}</div>}
export function EmptyState({children,title="Nothing here yet",description,desc,icon,actions,className,...props}:{children?:ReactNode;title?:ReactNode;description?:ReactNode;desc?:ReactNode;icon?:ReactNode;actions?:ReactNode;className?:string}&HTMLAttributes<HTMLDivElement>){return <div {...props} className={cn("rounded-lg border border-dashed border-line bg-card p-8 text-center",className)}>{icon ? <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-ink/5 text-ink-2">{icon}</div> : null}<h3 className="text-sm font-semibold text-ink">{title}</h3>{(description ?? desc) ? <p className="mt-1 text-xs text-ink-3">{description ?? desc}</p> : null}{actions ? <div className="mt-4 flex items-center justify-center gap-2">{actions}</div> : null}{children}</div>}
export function Modal({open,onClose,title,children,className,...props}:{open?:boolean;onClose?:()=>void;title?:ReactNode;children?:ReactNode;className?:string}&HTMLAttributes<HTMLDivElement>){if(!open)return null;return <div {...props} className={cn("fixed inset-0 z-50 flex items-center justify-center bg-ink/40 p-4",className)} onMouseDown={onClose}><div className="w-full max-w-lg rounded-xl border border-line bg-card p-5 shadow-card" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between gap-4">{title?<h2 className="font-semibold text-ink">{title}</h2>:<span/>}{onClose?<button type="button" onClick={onClose} className="text-ink-3 hover:text-ink" aria-label="Close">×</button>:null}</div><div className="mt-4">{children}</div></div></div>}
export function Skeleton({className,...props}:{className?:string}&HTMLAttributes<HTMLDivElement>){return <div {...props} className={cn("animate-pulse rounded-md bg-ink/10",className)} aria-hidden />}
export function Input({className,...props}:InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={cn("h-11 w-full rounded-md border border-line bg-card px-3 text-[13.5px] text-ink outline-none placeholder:text-ink-3 focus:border-pine/50 focus:ring-2 focus:ring-pine/10",className)}/>}
export function Select({className,...props}:SelectHTMLAttributes<HTMLSelectElement>){return <select {...props} className={cn("h-11 w-full rounded-md border border-line bg-card px-3 text-[13.5px] text-ink outline-none focus:border-pine/50 focus:ring-2 focus:ring-pine/10",className)}/>}
export function Field({label,children,className}:{label:string;children:ReactNode;className?:string}){return <label className={cn("block",className)}><span className="mb-1.5 block text-[12px] font-medium text-ink-2">{label}</span>{children}</label>}
